### PR TITLE
DOCKER-347 Added builds for Alfresco 5.2.6 and 5.2.7 enterprise

### PR DESCRIPTION
**Pull request by kpiot123**

### CODE REVIEW

**Comment by tgeens** [comment]
I see 2 main set of changes in this PR:
* updating gradle, gradle plugins, travis build
* bumping Share version

And why does the PR title mention both 5.2.6 and 5.2.7 ?

**Comment by tgeens** [comment]
I know you just wanted to bump the version and ran into issues. The famous Kent Beck once said:

> For each desired change, make the change easy (warning: this may be hard), then make the easy change

_Once_, means not too many years ago, on twitter: https://twitter.com/KentBeck/status/250733358307500032 ;-)

**Comment by kpiot123** [comment]
> I know you just wanted to bump the version and ran into issues. The famous Kent Beck once said:
> 
> > For each desired change, make the change easy (warning: this may be hard), then make the easy change
> 
> _Once_, means not too many years ago, on twitter: https://twitter.com/KentBeck/status/250733358307500032 ;-)

Yes, I will revert some changes and create a ticket to apply them again. I guess we got a bit too enthusiastic yesterday.

**Comment by vierbergenlars** [comment]
> Yes, I will revert some changes and create a ticket to apply them again.

I think squashing some of some of the try-out commits would not be bad either.
Let's first do upgrading the build and fixing it in this PR, and then create a new PR to add a new share version

**Pull request closed without merging**
