### PR TITLE
Allow to mount a custom share-config-custom.xml

### PR DESCRIPTION
**Pull request by anghelutar**
Do not use "sed -i", because that changes the inode of the file => share-config-custom.xml cannot be mounted.

Writing a new file and dumping its content later into the original is ok.

### CODE REVIEW

**Comment by anghelutar** [comment]
@vierbergenlars are you ok with this PR?

**Review by vierbergenlars — COMMENTED** [review]
Hmm, I missed this one.
I actually am not really okay with this, because it will also clobber the `share-config-custom.xml` when it is mounted, which I think is not supposed to happen, because:
 * A container is not supposed to change configuration files on the host that are given to it as additional configuration
 * It will fail startup when this file is mounted read-only.

**Comment by vierbergenlars** [comment]
To clarify: I am okay with rewriting that URL, but only when the file is inside the container, not when it is mounted from the outside.

**Comment by anghelutar** [comment]
Partially agree with your comments. I think if the file is mounted read-write, it should allow for edits via the init script.

Would a check of permissions be enough? If read-only - do nothing, otherwise - existing code.

**Comment by vierbergenlars** [comment]
I asked @Jasper-Hilven about his expectations when mounting a configuration file (just to have a third person). He also does not expect an externally provided file to be changed.
He did suggest an approach that seems like a good alternative to me: Keep the original input file unmodified and write a copy with replacements applied to the correct place.

In this case, this would mean moving the `share-config-custom.xml` file to someplace else, and then running `sed` with that file as input and the current location as output.
Additionally, that would guarantee idempotence when the container is restarted, since you are not doing the replacement again on the already modified file.

**Comment by anghelutar** [comment]
I am not sure I understand, can you push a commit? @vierbergenlars @Jasper-Hilven

**Comment by vierbergenlars** [comment]
This is what I mean. But I'm not sure this is a good location to read from, or that we want to standardize to a certain path with configfiles to be templated.

**Comment by vierbergenlars** [comment]
Instead of doing a sed here, we can also go one further and use `envsubst`, so you can use any environment variables in here.
If that works without having to escape too much things in the xml, then we have a nicer way to template it

**Comment by anghelutar** [comment]
Templating share-config-custom.xml is elegant. But, how would things like CSRF be templated? (before 6.1)

Alfresco uses sed:
https://github.com/Alfresco/share/blob/master/packaging/docker/substituter.sh

**Comment by vierbergenlars** [comment]
> Templating share-config-custom.xml is elegant. But, how would things like CSRF be templated? (before 6.1)

Well, if you require origin and referrer to always be set in envvars, then it's easy. If not, a similar sed is the best we can do (without going all-in and using an xml editor to change variables)

**Review by vierbergenlars — APPROVED** [review]

**Pull request merged**
